# Generated by Django 4.1.1 on 2022-09-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('MEDICO', 'Med'), ('ENFERMER@', 'Enf'), ('PACIENTE', 'Pac'), ('FAMILIAR', 'Fam'), ('AUXILIAR', 'Aux')], default='PACIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='create_date',
            field=models.DateField(verbose_name='Create_date'),
        ),
    ]
