# Generated by Django 4.1.1 on 2022-09-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_alter_auxiliar_cargo_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='username'),
        ),
    ]
