# Generated by Django 4.1.1 on 2022-09-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_alter_usuario_password_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default=12, max_length=30, verbose_name='direccion'),
            preserve_default=False,
        ),
    ]
